# Example configuration demonstrating multiple networks and custom labels.
port: 9090

networks:
  solana_mainnet:
    rpc_url: "https://api.mainnet-beta.solana.com"
    validators:
      - vote_address: "YOUR_MAINNET_VOTE_ACCOUNT_PUBKEY"
        identity_address: "YOUR_MAINNET_IDENTITY_ACCOUNT_PUBKEY"
        # optional and it overrides the network-level labels
        labels:
          description: "SOME_DETAILS_FOR_THIS_VALIDATOR"
      # - vote_address: "OPTIONAL_SECOND_MAINNET_VOTE_ACCOUNT"
      #   identity_address: "OPTIONAL_SECOND_MAINNET_IDENTITY_ACCOUNT"
    labels:
      stage: mainnet
      environment: production

  solana_testnet:
    rpc_url: "https://api.testnet.solana.com"
    validators:
      - vote_address: "YOUR_TESTNET_VOTE_ACCOUNT_PUBKEY"
        identity_address: "YOUR_TESTNET_IDENTITY_ACCOUNT_PUBKEY"
    # labels: {}

  # solana_devnet:
  #   rpc_url: "https://api.devnet.solana.com"
  #   validators:
  #     - vote_address: "YOUR_DEVNET_VOTE_ACCOUNT_PUBKEY"
  #       identity_address: "YOUR_DEVNET_IDENTITY_ACCOUNT_PUBKEY"
  #   labels:
  #     stage: devnet
